<?php
/**
 * AffiliateApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Solifyn\Test\Api;

use \Solifyn\Configuration;
use \Solifyn\ApiException;
use \Solifyn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AffiliateApiTest Class Doc Comment
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AffiliateApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for affiliateControllerApproveConnection
     *
     * .
     *
     */
    public function testAffiliateControllerApproveConnection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerArchiveConnection
     *
     * .
     *
     */
    public function testAffiliateControllerArchiveConnection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerDeleteOverride
     *
     * .
     *
     */
    public function testAffiliateControllerDeleteOverride()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerGetEarningsConnections
     *
     * .
     *
     */
    public function testAffiliateControllerGetEarningsConnections()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerGetEarningsLedger
     *
     * .
     *
     */
    public function testAffiliateControllerGetEarningsLedger()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerGetEarningsStats
     *
     * .
     *
     */
    public function testAffiliateControllerGetEarningsStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerGetMarketplace
     *
     * .
     *
     */
    public function testAffiliateControllerGetMarketplace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerGetProgramConnections
     *
     * .
     *
     */
    public function testAffiliateControllerGetProgramConnections()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerGetProgramLedger
     *
     * .
     *
     */
    public function testAffiliateControllerGetProgramLedger()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerGetProgramSettings
     *
     * .
     *
     */
    public function testAffiliateControllerGetProgramSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerJoinProgram
     *
     * .
     *
     */
    public function testAffiliateControllerJoinProgram()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerRejectConnection
     *
     * .
     *
     */
    public function testAffiliateControllerRejectConnection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerSaveOverride
     *
     * .
     *
     */
    public function testAffiliateControllerSaveOverride()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for affiliateControllerSaveProgramSettings
     *
     * .
     *
     */
    public function testAffiliateControllerSaveProgramSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
