<?php
/**
 * CommunityApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Solifyn\Test\Api;

use \Solifyn\Configuration;
use \Solifyn\ApiException;
use \Solifyn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CommunityApiTest Class Doc Comment
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CommunityApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for communityControllerCreatePost
     *
     * .
     *
     */
    public function testCommunityControllerCreatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for communityControllerDeletePost
     *
     * .
     *
     */
    public function testCommunityControllerDeletePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for communityControllerGetPosts
     *
     * .
     *
     */
    public function testCommunityControllerGetPosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for communityControllerLikePost
     *
     * .
     *
     */
    public function testCommunityControllerLikePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for communityControllerReportPost
     *
     * .
     *
     */
    public function testCommunityControllerReportPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for communityControllerSharePost
     *
     * .
     *
     */
    public function testCommunityControllerSharePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for communityControllerUnlikePost
     *
     * .
     *
     */
    public function testCommunityControllerUnlikePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for communityControllerUpdatePost
     *
     * .
     *
     */
    public function testCommunityControllerUpdatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
