<?php
/**
 * DeveloperApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Solifyn\Test\Api;

use \Solifyn\Configuration;
use \Solifyn\ApiException;
use \Solifyn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DeveloperApiTest Class Doc Comment
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeveloperApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for developerControllerCreateApiKey
     *
     * .
     *
     */
    public function testDeveloperControllerCreateApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerCreateWebhookEndpoint
     *
     * .
     *
     */
    public function testDeveloperControllerCreateWebhookEndpoint()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerDeleteApiKey
     *
     * .
     *
     */
    public function testDeveloperControllerDeleteApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerDeleteWebhookEndpoint
     *
     * .
     *
     */
    public function testDeveloperControllerDeleteWebhookEndpoint()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerGetApiKeys
     *
     * .
     *
     */
    public function testDeveloperControllerGetApiKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerGetAppPortalUrl
     *
     * .
     *
     */
    public function testDeveloperControllerGetAppPortalUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerGetWebhookDeliveries
     *
     * .
     *
     */
    public function testDeveloperControllerGetWebhookDeliveries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerGetWebhookEndpoints
     *
     * .
     *
     */
    public function testDeveloperControllerGetWebhookEndpoints()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for developerControllerUpdateWebhookEndpoint
     *
     * .
     *
     */
    public function testDeveloperControllerUpdateWebhookEndpoint()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
