<?php
/**
 * TicketApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Solifyn\Test\Api;

use \Solifyn\Configuration;
use \Solifyn\ApiException;
use \Solifyn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TicketApiTest Class Doc Comment
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TicketApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for ticketControllerCreateTicket
     *
     * .
     *
     */
    public function testTicketControllerCreateTicket()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ticketControllerGetTicketDetails
     *
     * .
     *
     */
    public function testTicketControllerGetTicketDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ticketControllerGetTickets
     *
     * .
     *
     */
    public function testTicketControllerGetTickets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ticketControllerReplyTicket
     *
     * .
     *
     */
    public function testTicketControllerReplyTicket()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ticketControllerUpdateTicket
     *
     * .
     *
     */
    public function testTicketControllerUpdateTicket()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
